apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: n6tzflk27-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/n6tzflk27-java-quarkus-gitops